### ISSUE TITLE
Reporting of empty lines as not covered

### ISSUE THREAD

**Issue by ir-fuel** [bcoe/c8#112]
* **Version**: Node v10.15.3
* **Platform**: Darwin Kernel Version 18.5.0

After running my tests I get a coverage report that reports empty lines as being uncovered.

This is one of the files where it does this:
```
const config = require("config");
const logger = require("./logger");

const geocoderConfig = config.geocoder
const apiKey = geocoderConfig.apiKey;
const extra = {
  apiKey: apiKey,
  timeout: 30000
};

const geocoder = require("node-geocoder")("google", "https", extra);

exports.geocode = (address, zip, city, country) => {

  let params = {
    address: address + ' ' + zip + ' ' + city + ' ' + country
  };

  return new Promise((resolve, reject) => {
    geocoder.geocode(
      params, (error, result) => {

        /* c8 ignore next 3 */
        if (error) {
          logger.error("Error geocoding: " + JSON.stringify({error, result}, null, 3));
          return reject(error);
        }

        /* c8 ignore next 5 */
        if (!result || result.length === 0)
          return resolve({
            latitude: null,
            longitude: null
          });

        resolve({
          latitude: result[0].latitude,
          longitude: result[0].longitude
        });
      });
  });
};

```

The empty line right above `c8 ignore next 3` is reported as uncovered

```
---------------------------|----------|----------|----------|----------|-------------------|
File                       |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
---------------------------|----------|----------|----------|----------|-------------------|
All files                  |    78.38 |    64.79 |    84.99 |    78.38 |                   |
  geocoder.js              |    97.62 |    71.43 |      100 |    97.62 |                22 |
```

I also have other files where it reports closing braces as uncovered, e.g. at the end of a file I have
```
      })
  })
}
```

and those 3 lines are reported as uncovered.

**Comment by shinnn** [comment]
Try to creating a minimal reproduction. It would be very helpful if you can provide an example with 10 lines or smaller. ref. https://github.com/bcoe/c8/issues/61#issue-406650176

Also, don't leave us guessing. The code at least should have told us how the exported `geocode` function is called.

**Comment by ir-fuel** [comment]
Ok nvm. I removed `esm` from my project, converted all `import` statements to `require` and I'm back to using Istanbul.

**Comment by shinnn** [comment]
As long as https://github.com/bcoe/c8/issues/112#issue-453804759 lacks the information you're using [`esm`](https://github.com/standard-things/esm) and the example contains no `import` statement, we could never provide any useful feedback for you because we could hardly guess both of them from the issue description.

**Comment by sramam** [comment]
Please see for a simple reproduction.
https://github.com/sramam/c8-empty-lines

My experiments seem to indicate that it only happens for files that `export * ...`.
