### ISSUE TITLE
Add command line option to turn off the outputReport

### ISSUE THREAD

**Issue by gabrielschulhof** [bcoe/c8#114]
Node.js: 12.4.0
c8: 5.0.1
Platform: Linux eagle 5.1.7-300.fc30.x86_64 #1 SMP Wed Jun 5 12:32:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

My test suite runs child processes and the decision as to whether to run them through c8 is passed along as a command line argument. The child processes output a JSON object which is parsed from their stdout to assert correctness. The unconditional production of c8's `outputReport()` interferes with the `JSON.parse()` of the child process' `stdout`.

Commenting out [these lines](https://github.com/bcoe/c8/blob/master/bin/c8.js#L38-L43) is a workaround. It'd be nice if they could be turned off with a command line parameter.

**Comment by shinnn** [comment]
You can achieve essentially the same thing with the [`none` reporter](https://istanbul.js.org/docs/advanced/alternative-reporters/#none).

```console
$ c8 node run.js
Hello
----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |      100 |      100 |      100 |      100 |                   |
 run.js   |      100 |      100 |      100 |      100 |                   |
----------|----------|----------|----------|----------|-------------------|

$ c8 --reporter=none node run.js
Hello
```

**Comment by gabrielschulhof** [comment]
@shinnn thank you!
