### ISSUE TITLE
Question: how does --include work

### ISSUE THREAD

**Issue by behalka** [bcoe/c8#115]
* **Version**: v10.15.2

Hi, I have a question about `--include` parameter. I have tried to target a specific file (`--include ["src/api/foo.ts"]`) and to use a glob pattern (`--include ["src/**"]`) but the only thing I got was a completely empty report. Am I using this parameter correctly?

Btw I run tests with `ts-node` (I guess that could be important. Even though the basic c8 usage works perfectly :)

Thanks a lot!

**Comment by shinnn** [comment]
Though I'm unfamiliar with the internals of [ts-node](https://github.com/TypeStrong/ts-node), I guess it

1. compiles `.ts` files with TypeScript compiler
2. stores the generated pure JavaScript code to memory or a temporary file
3. runs the generated code

If the compiled JavaScript contains a source map for the original `src/api/foo.ts`, `c8` should collect its coverage regardless of `--include` option value.

@behalka Can you check if `ts-node` includes source map to the compiled JavaScript or not?

**Comment by behalka** [comment]
Hi @shinnn thanks for your feedback. I did some digging and `ts-node` by default should include source maps (based on comments to some issues in their repo). Then I tried to compare and get some ideas from there https://www.npmjs.com/package/@istanbuljs/nyc-config-typescript.

Their solution worked for me so that's how I "solved" this issue. Thanks a lot for your time & happy coding :)

**Comment by scythargon** [comment]
@behalka Hello!:) Have you figured out how to properly use the `--include`? Could you please share this wisdom?
