### ISSUE TITLE
Jest doesn’t support V8 built-in coverage reporting

### ISSUE THREAD

**Issue by scythargon** [bcoe/c8#126]
Hi! 
I've found this thread https://github.com/bcoe/c8/issues/115 but still haven't figured out the answer. 
How to use `--include` properly? 
I want to calculate the coverage for the whole project.
Tried like this for example:
`"test": "NODE_ENV=test NODE_V8_COVERAGE=coverage c8 --include [\"**/*.{js,jsx}\"] jest --color --forceExit --detectOpenHandles --maxWorkers=5",`  but also got only empty report (not empty without `--include`)
BTW there is no config file currently, right? Only CLI parameters.
(yeah, I know that there is a built in `nyc` coverage in the `jest`, but it does not work very stable with `styled-jsx` package - https://github.com/zeit/styled-jsx/issues/436 that's why I'm looking for an alternative coverage tool)

**Comment by shinnn** [comment]
`--include` is totally unrelated to this issue. The real problem is that the current version of Jest doesn’t work well with V8 coverage. Wait for https://github.com/facebook/jest/pull/8596 to be merged and you’ll be able to use `jest`’s `--v8-coverage` option instead of `c8`.

**Comment by shinnn** [comment]
Anyway, fill in the issue template next time.

**Comment by bcoe** [comment]
@scythargon :wave: I'm sure @SimenB would love additional folks to help out with testing Jest's built in coverage functionality :+1: I recommend joining in on that thread that @shinnn linked to.

I'm not quite sure the specifics of why Jest and c8 would be incompatibile, I would think it would work for the simple case of:

```
c8 jest foo.js
```

Where I believe problems might arise would be in source-maps, which I believe is being addressed in the work on `#8596`.

**Comment by bcoe** [comment]
to @shinnn's point, it's easier for us to help debug if you can provide a snippet of code or repo that demonstrates the issue you're having ... in your case however, I think you'll find the experimental branch in Jest helps a ton.
