### ISSUE TITLE
Deprecated Buffer usage in dependency

### ISSUE THREAD

**Issue by oliversalzburg** [bcoe/c8#136]
* **Version**: 5.0.2
* **Platform**: Windows

Every time I start c8, I get the following warning:
`(node:12776) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.`

This is because `foreground-child` uses `cross-spawn`, which uses `new Buffer()`.

`cross-spawn` has recently finally [resolved this issue](https://github.com/moxystudio/node-cross-spawn/commit/16feb534e818668594fd530b113a028c0c06bddc), but it'll probably take quite some time until the change trickles downstream.

Maybe an alternative module without deprecate feature usage can be used instead?

**Comment by bcoe** [comment]
@oliversalzburg this should be addressed in `5.0.3`.
