### ISSUE TITLE
Different coverage reported on Windows vs Linux

### ISSUE THREAD

**Issue by oliversalzburg** [bcoe/c8#137]
* **Version**: 5.0.2
* **Platform**: Linux runner-4xz_xPE1-project-77-concurrent-0 4.4.0-1052-aws #61-Ubuntu SMP Mon Feb 12 23:05:58 UTC 2018 x86_64 GNU/Linux

I get differing coverage reports depending on if I run the test on Windows 10 x64 vs Ubuntu x64. Both platforms are running Node 12.9.1. The issue seems to only affect specific files in the test suite/application.

### Windows
![image](https://user-images.githubusercontent.com/1658949/63897443-6cbce500-c9f5-11e9-8945-1f129c37166c.png)

### Ubuntu
![image](https://user-images.githubusercontent.com/1658949/63897462-79413d80-c9f5-11e9-9e26-ba6a02d5fe64.png)

The pattern is always the same in all affected files. The imports are shown as not covered and so is the class and method declaration.

When I tried to isolate the behavior in a smaller projects, I was not able to. Any suggestions on how to approach this so I can get more useful information?

**Comment by bcoe** [comment]
@oliversalzburg could you provide a repository with a minimal reproduction of the issue you're seeing?

**Comment by oliversalzburg** [comment]
I actually tried working on one for a while, but when I removed all our private dependencies, I was no longer to reproduce the issue :(

I was hoping someone might have an idea of why this is happening so I could investigate into a certain area. I will try my luck again with a repro and report back.

**Comment by bcoe** [comment]
👍 are you using anything that transpiles code, like Babel, TypeScript, or ESM?

**Comment by oliversalzburg** [comment]
I'm not. This is plain JS running in Node.

**Comment by oliversalzburg** [comment]
Ugh, can't reproduce it at work at all right now. Either the code has changed so that the issue no longer appears or it's something special about my home workstation. I'll check it out tonight.
