### ISSUE TITLE
question: how use it with typescript using ts-node

### ISSUE THREAD

**Issue by Oloompa** [bcoe/c8#139]
Hello,

I use **typescript** and **ava** for unit test. I write my test in typescript.

With istanbul i can run test using `npx nyc ava --verbose` with a config file for ava and an other for istanbul.

Ava compile typescript files on the fly.

If i run `npx c8 ava --verbose` i get coverage but if i check in my ide (vscode) i got strange indication. It'maybe due to c8 not using sourcemap ?

![image](https://user-images.githubusercontent.com/51793308/64321446-d5d9c500-cfc0-11e9-8202-4a1301498603.png)

Maybe i am doing something wrong. A recipe for use C8 with  typescript compilation on the fly would be welcome.

Can you help ?

**Comment by Oloompa** [comment]
finally i moved for compile first and test after
better for CI/CD optimisation

**Comment by bcoe** [comment]
@Oloompa there's work happening here:

https://github.com/nodejs/node/pull/28960

that would allow ts-node to be supported; I'm glad you're unblocked however.

**Comment by make-github-pseudonymous-again** [comment]
Do I understand correctly that on-the-fly-transpiled source coverage works correctly now in c8? I assume that given the test examples

https://github.com/bcoe/c8/blob/ff01cd832a155494892b24c30c5a1c8f0169fd8e/test/integration.js#L452-L464

and

https://github.com/bcoe/c8/blob/ff01cd832a155494892b24c30c5a1c8f0169fd8e/test/integration.js#L507-L519

the way to go is via `ts-node` [which `AVA` uses](https://github.com/avajs/ava/blob/f09742f7baab7d44a48f1e3cee8f4b22deecf6f4/docs/recipes/typescript.md#using-ts-node).

Is there a case for adding TypeScript coverage related documentation to the README?

**Comment by bcoe** [comment]
> Is there a case for adding TypeScript coverage related documentation to the README?

Perhaps a short blurb? for the most part there's nothing special you need to do for `c8` as long as the source maps are there.
