### ISSUE TITLE
Uncovered branches (in html report) not highlighted

### ISSUE THREAD

**Issue by stevenvachon** [bcoe/c8#159]
* **Version**: 6.0.1
* **Platform**: Darwin Stevens-Mac-mini.local 19.0.0 Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64 x86_64

The generated HTML report says "95.83% Branches 23/24", but the uncovered branch is not highlighted anywhere. With istanbul previously, such were highlighted in yellow.

**Comment by bcoe** [comment]
@stevenvachon what version of Node.js are you using? There were some bugs related to this addressed relatively recently in V8 itself; Check if the problem persists on Node 13.

If the issue does persist, could you please link a repository that demonstrates the issue.

**Comment by bcoe** [comment]
👋 @stevenvachon please feel free to reopen if this continues to be an issue, I'm guessing this was addressed in newer versions of Node.js.
