### ISSUE TITLE
Improve c8 determinism

### ISSUE THREAD

**Issue by demurgos** [bcoe/c8#16]
`c8` uses `uuid.v4` to generate unique file names:

https://github.com/bcoe/c8/blob/f14508e0a1a2625252193ecc4c6500961cc6a7a2/lib/wrap.js#L76

This introduces randomness. This is bad because it prevents reproducible execution in case an issue is found. For example #14 has a bug that depends on the order in which the result files are loaded.

`c8` needs unique names, not random names. Given that `c8` clears its temporary directory every time it runs, a counter should be enough for uniqueness. We could also improve the output slightly by using the url of the test file. Something like:
```js
const digits = (allV8Coverage.length - 1).toString(10).length;
for (let i = 0; i <allV8Coverage.length; i++) {
  const v8 = allV8Coverage[i];
  const baseName = path.posix.baseName(v8.url); // Not the exact code
  const fileName = `${i.toString(10).padStart(digits, "0")}-${baseName}.json`;
  // ...
}
```

The code above is determinist if `allV8Coverage` is.

**Comment by demurgos** [comment]
I've looked into it more carefully. My solution above would not work. `c8` uses `spawn-wrap`. This is a crazy hack allowing to intercept when Node is spawned. This means that the `wrap` script may be called many times if the process tree spawns Node many times. My solution assumed that `wrap` was executed only once.

**Comment by demurgos** [comment]
I think that it's possible to get rid of the temporary files. This should provide the cleanest solution.

**Comment by ProfNandaa** [comment]
@demurgos -- what's the way forward on this?

**Comment by demurgos** [comment]
The new `c8` no longer use any random values so it's good.
The only remaining issue is determinism regarding the names of coverage files written by `Node`. They're using process ids and timestamps so it's better. The only improvement IMO would be to move the timestamp first and zero-pad the values to reduce the impact of the process manager.

**Comment by bcoe** [comment]
@demurgos probably worth opening this issue on Node.js, proposing the change in ID order? I'm going to close the issue here.
