### ISSUE TITLE
Branch coverage wrong

### ISSUE THREAD

**Issue by pke** [bcoe/c8#174]
* **Version**: node 12.11.0, c8 3.0.3
* **Platform**: Linux htpc 4.4.0-161-generic #189-Ubuntu SMP Tue Aug 27 08:10:16 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

I am getting a single branch uncover in line 35 which looks like this:
![image](https://user-images.githubusercontent.com/164625/70908267-0f33bf00-200b-11ea-9cc8-5164a1d097a8.png)

![image](https://user-images.githubusercontent.com/164625/70908294-25417f80-200b-11ea-93d8-8b3e17e09674.png)

What could be the cause of that?

**Comment by bcoe** [comment]
@pke could you provide a minimal reproduction in a repository? I believe this issue is already fixed upstream in `V8` and related to the handling of default parameters in functions.

**Comment by pke** [comment]
Thanks for the fast feedbac, I'll publish my code in a minute. Its a small webserver

**Comment by bcoe** [comment]
@pke 👋 I believe this has been fixed for a while, please let me know if you continue to bump into issues.

**Comment by pke** [comment]
I'll check and report back here later.
