### ISSUE TITLE
Feature: Support for reason in `c8 ignore` comments

### ISSUE THREAD

**Issue by coreyfarrell** [bcoe/c8#181]
istanbuljs supports giving a reason for ignoring coverage, for example:
```js
/* istanbul ignore next: paranoid check */
```

I think the ability to give a reason for ignoring coverage is very valuable.  With projects that use istanbuljs for coverage I'll run `git grep 'istanbul\s*ignore'` periodically to check for any improperly ignored coverage.

**Comment by bcoe** [comment]
Thanks for the contribution!

https://github.com/istanbuljs/v8-to-istanbul/pull/203
