### ISSUE TITLE
Simple switch statements are ignored

### ISSUE THREAD

**Issue by schmidt-sebastian** [bcoe/c8#185]
The coverage report for the `@google-cloud/firestore` says the code in simple switch statements is not executed:

<img width="592" alt="Screen Shot 2020-01-03 at 9 41 28 AM" src="https://user-images.githubusercontent.com/19397744/71739051-411b9280-2e0d-11ea-9d95-28a484eb8750.png">

This code is however tested via https://github.com/googleapis/nodejs-firestore/blob/5000b2d4b5c528b66c5a71db343c0e4163d5d8f7/dev/test/order.ts#L147

In general, it looks like there is some accounting error with the last line, which would explain why one-line case statements are completely ignored:

<img width="652" alt="Screen Shot 2020-01-03 at 9 44 14 AM" src="https://user-images.githubusercontent.com/19397744/71739233-b4250900-2e0d-11ea-8d3c-2ec6d481bf89.png">

**Comment by bcoe** [comment]
@schmidt-sebastian mind trying this with Node 12, or Node 13, I believe this was an issue with V8 that was already addressed (I at least can't reproduce with a simple example locally).

**Comment by schmidt-sebastian** [comment]
This is indeed fixed in Node 12 (tested with 12.14):

<img width="295" alt="Screen Shot 2020-01-03 at 10 41 56 AM" src="https://user-images.githubusercontent.com/19397744/71742156-ae332600-2e15-11ea-98a3-8040a8a7b345.png">
