### ISSUE TITLE
[feat] add typescript types for report.js

### ISSUE THREAD

**Issue by Toxicable** [bcoe/c8#195]
Im using c8/lib/report to merge and convert coverage reports under bazel and it would be great if there were types so it's easier to use this as a dep.
happy to submit a PR, let me know if this is something you'd want.

**Comment by Toxicable** [comment]
See https://github.com/bazelbuild/rules_nodejs/pull/1135/files#diff-cf68df009e956fdc1b73ff16773264f1

**Comment by bcoe** [comment]
@Toxicable I would happily accept a PR, excited to have more folks using the library.
