### ISSUE TITLE
c8 tries to read soruce file, when inline source file content is avilable

### ISSUE THREAD

**Issue by Toxicable** [bcoe/c8#197]
Similar to #195 I'm implmenting c8 into bazel.
An issue i've come accross is where c8, or maybe v8-to-istanbul is trying to read the source file, when instead it has the source file content avilable in the source map.

Is there some other reason why c8 cant use the source file content from the source map?

Due to the way that bazel lays out the run directory it's not possible to gett back to the source file from the source map without rewriting the source map path, which there is no API for.
But even so I think it would be best to just use the source file content if avilable

**Comment by Toxicable** [comment]
Modifying v8-to-istanbul to do 
```
        if(this.sources.sourceMap.sourcemap.sourcesContent.length === 1) {
          originalRawSource = this.sources.sourceMap.sourcemap.sourcesContent[0]
        } else if (this.sources.originalSource) {
          originalRawSource = this.sources.originalSource
        } else {
          originalRawSource = await readFile(this.path, 'utf8')
        }
```
instead of it's currentt logic 
```
        if (this.sources.originalSource) {
          originalRawSource = this.sources.originalSource
        } else {
          originalRawSource = await readFile(this.path, 'utf8')
        }
```
Fixed my problem, would you be happy adding this change in?

**Comment by Toxicable** [comment]
Ah shoot, while it can do a `text` and `text-summary` reportt witth this modification, it fails if we use `html`.

I think it's still worth while doing it, but might need another method to set tthe sourceRoot or rewrite the source paths later on

**Comment by Toxicable** [comment]
Actually  I think the html part is fine, we're actually plannning on just going to lcov format, then do another transform to html later on, when we go to html we can rewrite the sourcemaps then

**Comment by bcoe** [comment]
hey @Toxicable happy to make this change to v8-to-istanbul :ok_hand:, I'm a little slammed today, want to submit a patch if you have a second? otherwise I'll try to get to it soon.

**Comment by Toxicable** [comment]
Sure, opened a PR here https://github.com/istanbuljs/v8-to-istanbul/pull/85

**Comment by Toxicable** [comment]
closed via https://github.com/istanbuljs/v8-to-istanbul/pull/85
