### ISSUE TITLE
outputting coverage when process.exit() is called

### ISSUE THREAD

**Issue by bcoe** [bcoe/c8#2]
I think @chrisdickonson came up with a good idea for how to approach this, if we capture an event on process.exit, we'll use `spawnSync` to output coverage in a subprocess.

```js
const client = await CRI({port: port})
const {Profiler} = client

process.on('exit', () => {
  process.spawnSync('ws-write-coverage.js', ())
  client.close()
})
```

CC: @schuay, @bmeck

**Comment by schuay** [comment]
It'd be awesome to solve this using the current V8 API; but if that turns out to be a bad solution I could imagine emitting an inspector event on Isolate teardown containing all remaining coverage information. Just an idea so far, not sure how happy inspector folks would be about that.

cc @hashseed, @caseq

**Comment by bcoe** [comment]
@schuay looping in @TimothyGu and @eugeneo, who look to have done a chunk of the work on the Inspector binding in Node.js.

The approach I outlined above doesn't quite work. Calling `inspector.close()` in the context of `process.exit()` seems to hang the Node process... `process.exit` is a weird method, in that it can only perform synchronous operations, and the even loop is guaranteed to exit on the next tick (my guess is that `inspector.close()` steps on the toes of the shutdown process).

Even though this is potentially a bug we can fix in Node, as you point out @schuay, it might be a bit nicer to change around the API a bit so that you can more easily execute an operation as soon as your application has completed execution; maybe I'm just missing something?

**Comment by bcoe** [comment]
digging into this a bit more, I was able to get things to terminate in `process.exit()` _but_ by the time we've hit `process.exit()` I believe the inspector session is already terminated so it's not possible to use `spawnSync` to communicate with the parent process.

**Comment by TimothyGu** [comment]
How about [`process.on('beforeExit')`](https://nodejs.org/api/process.html#process_event_beforeexit)?

**Comment by bcoe** [comment]
@TimothyGu good idea, I called `unref` on the socket connecting to the inspector, and switched to a `beforeExit` handler:

https://github.com/bcoe/c8/pull/4

This seems to work well if the application exits normally, or if the application throws an exception. If the program exits due to a `process.exit(0)`, `beforeExit` does not fire (am I missing something, haven't used this hook before)?

this is definitely progress!

**Comment by bcoe** [comment]
there's an event that fires when a script finishes execution that we can wire into.
