### ISSUE TITLE
Support ignore rules

### ISSUE THREAD

**Issue by demurgos** [bcoe/c8#21]
`nyc` and `istanbul` let you use ignore rules such as `istanbul ignore next` or `istanbul ignore else`.
It would be good to support those too. We could support the prefix `c8` or more general `coverage` so you could write `c8 ignore next` or `coverage ignore else`.

Of course, V8 would return coverage even for the ignored parts, but they should not be included in the final report.

This may be a `v8-to-istanbul` issue.

**Comment by bcoe** [comment]
I think it would be good to start with the simple rule, `ignore next`, which would ignore the next line; this should be fairly easy to implement in `v8-to-istanbul`.

**Comment by bcoe** [comment]
this is done 😄

**Comment by pke** [comment]
So which rules are supported yet? @bcoe

**Comment by bcoe** [comment]
@pke https://github.com/bcoe/c8#ignoring-the-next-element
