### ISSUE TITLE
bug: file missing from coverage

### ISSUE THREAD

**Issue by mikeal** [bcoe/c8#232]
* **Version**: 7.2.0
* **Platform**: Linux, Node.js v14.5.0

I’m seeing this error:

```
file: /root/brrp/src/rollup-iter.js error: TypeError: Cannot read property 'sources' of null
    at V8ToIstanbul.load (/root/brrp/node_modules/v8-to-istanbul/lib/v8-to-istanbul.js:46:34)
    at Report.getCoverageMapFromAllCoverageFiles (/root/brrp/node_modules/c8/lib/report.js:88:25)
    at async Report.run (/root/brrp/node_modules/c8/lib/report.js:59:20)
    at async exports.outputReport (/root/brrp/node_modules/c8/lib/commands/report.js:27:3)
    at async /root/brrp/node_modules/c8/bin/c8.js:39:9
```

As a result the file `src/rollup-iter.js` is missing from coverage and c8 passes the full coverage check :(

You can reproduce by running the tests in https://github.com/mikeal/brrp

Sorry for this being a little terse, I plan to return to this and debug a little bit more. It looks like it’s in `v8-to-istanbul` so I can at least track it down more, maybe even send a fix, but I wanted to get this logged before I forgot about it and moved on :)

**Comment by bcoe** [comment]
@mikeal we'll make an effort to patch this weekend.

**Comment by bcoe** [comment]
@mikeal okay, I have a fix incoming for this for c8, it uncovered a bug with Node.js' source map implementation which I am going to patch at the same time.
