### ISSUE TITLE
Is it possible to include node_modules in coverage reports?

### ISSUE THREAD

**Issue by mattriley** [bcoe/c8#250]
* **Version**: v14.4.0
* **Platform**: Darwin 192-168-1-103.tpgi.com.au 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64

I want to use the coverage report to understand the utilisation of my dependencies. I've tried to include node_modules with the --include option but it doesn't seem to work for me.

**Comment by j03m** [comment]
node_modules is included as one of the default strings we specifically ignore when generating a report. (here is a case exercised in our dep library `test-exclude` that illustrates that this is the desired behavior normally: https://github.com/istanbuljs/test-exclude/blob/b57e9368aacdd548981ffd2ab6447bbd2c1e7de0/test/test-exclude.js#L19

As such I think this is pretty hard wired. I'm not sure if this is a usecase we would support on the main repo without more input from users, but in theory you could fork this repo and `test-exclude` edit `test-exclude` not ignore `node_modules` by default.

I'll leave this open for now in case there is additional feedback.

**Comment by j03m** [comment]
7 days no comment, closing.
