### ISSUE TITLE
Erroneous report of missing coverage

### ISSUE THREAD

**Issue by sramam** [bcoe/c8#253]
c8 report seems to report lack of coverage for "export * from ...`. 
This is likely the same  as #112. I added a comment there, but noticed the
issue was closed. So filing a new one. 

Please see for a simple reproduction.
https://github.com/sramam/c8-empty-lines

My experiments seem to indicate that it only happens for files that export * ....

**Comment by sramam** [comment]
Looking at the report of a large (private) repo, it seems this is somehow tied to the EOF marker.
It's always the last line that is reported in the `--reporter text` report, and always the branch-coverage 
that falls short.

**Comment by bcoe** [comment]
Thank you for providing  reproduction @sramam. One thing worth trying, would be turning off source-maps.

It might be the case that TypeScript is actually adding an additional line of code in the built .js, which is legitimately not covered.

**Comment by sramam** [comment]
interesting thought.
turns out that the helper functions being emitted by `tsc` might have been the problem.

Installing `tslib` seems to resolve this problem.

```
$ git diff tsconfig.json
diff --git a/tsconfig.json b/tsconfig.json
index b33468a..67a043b 100644
--- a/tsconfig.json
+++ b/tsconfig.json
@@ -10,7 +10,8 @@
       "rootDir": "src",
       "removeComments": false,
       "outDir": "dist",
-      "incremental": true
+      "incremental": true,
+      "importHelpers": true
   },
   "exclude": [
       "node_modules",
```
```
$ git diff package.json
diff --git a/package.json b/package.json
index d3274aa..4ffa321 100644
--- a/package.json
+++ b/package.json
@@ -17,5 +17,8 @@
     "c8": "^7.3.1",
     "cross-env": "^7.0.2",
     "typescript": "^4.0.3"
+  },
+  "dependencies": {
+    "tslib": "^2.0.1"
   }
 }
```
```
> c8 report -r lcov -r text --report-dir ./.c8-report

(node:20604) ExperimentalWarning: Conditional exports is an experimental feature. This feature could change at any time
-----------|---------|----------|---------|---------|-------------------
File       | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
-----------|---------|----------|---------|---------|-------------------
All files  |     100 |      100 |     100 |     100 |
 src       |     100 |      100 |     100 |     100 |
  index.ts |     100 |      100 |     100 |     100 |
  main.ts  |     100 |      100 |     100 |     100 |
 src/test  |     100 |      100 |     100 |     100 |
  index.ts |     100 |      100 |     100 |     100 |
-----------|---------|----------|---------|---------|-------------------
```
