### ISSUE TITLE
Does c8 support config files?

### ISSUE THREAD

**Issue by marktyers** [bcoe/c8#274]
Rather than specifying the settings as flags is there support for including a config file (json format)?

This could be standalone, for example:
`.ava.config.json`

Or included in the package manifest `package.json`. Perhaps using the same format as **jest**?

```json
{
  "name": "my-project",
  "ava": {
    "coverageThreshold": {
      "global": {
        "branches": 80,
        "functions": 80,
        "lines": 80,
        "statements": -10
      }
  }
}
```

**Comment by bcoe** [comment]
@marktyers you can provide a `.nycrc.json` or a `.c8.json` configuration file. It accepts all the same keys accepted by the CLI:

https://github.com/bcoe/c8/blob/master/.nycrc

Seems like an oversight that it's not documented.

**Comment by bcoe** [comment]
Oh, I should also add, once you have this configuration file you can create a badge based on it:

https://shields.io/category/coverage

**Comment by XhmikosR** [comment]
@bcoe .nycrc works, but it seems a package.json config key of `nyc` does not work (it works with nyc, though). Is that supposed to work too?

**Comment by bcoe** [comment]
@XhmikosR for easy migration from old projects, I decided to support both `.c8rc` and `.nycrc`, for package configuration I think it was intentional that it supports only `c8`.

Sounds like you're unblocked?

**Comment by XhmikosR** [comment]
Yeah. But this issue is still valid; there's no documentation about which config files are supported :)

**Comment by SalahAdDin** [comment]
> @marktyers you can provide a `.nycrc.json` or a `.c8.json` configuration file. It accepts all the same keys accepted by the CLI:
> 
> https://github.com/bcoe/c8/blob/master/.nycrc
> 
> Seems like an oversight that it's not documented.

Yeah, it is not still documented, so, it is not clear.

**Comment by Wambosa** [comment]
for future engineers who just want a tldr example json

old `package.json`:
```
    "test:ci": "cross-env NODE_OPTIONS=--enable-source-maps npx c8 --check-coverage --branches 80 --functions 80 --lines 80 --statements 80 --exclude 'build/dev/unit/**' --exclude 'build/dev/mock/**' --reports-dir ./build/ jasmine --config=config/jasmine-unit.json",
```

translates to this config file (`/config/.c8rc`):
```
{
  "check-coverage": true,
  "reports-dir": "./build/",
  "branches": 80,
  "functions": 80,
  "lines": 80,
  "statements": 80,
  "exclude": [
    "build/dev/unit/**",
    "build/dev/mock/**"
  ]
}
```


which makes us update our `package.json` command to:
```
"test:ci2": "cross-env NODE_OPTIONS=--enable-source-maps npx c8 --config ./config/.c8rc jasmine --config=config/jasmine-unit.json",
```


ps love `c8`, been using it for years. Thank y'all 🙏
