### ISSUE TITLE
Ability to skip-full report with command line option

### ISSUE THREAD

**Issue by coderaiser** [bcoe/c8#286]
Thank you for such a great tool :).
Would be amazing to have ability to skip full report using command line option, like [in nyc](https://github.com/istanbuljs/nyc#common-configuration-options).
This would be very useful for monorepo projects like [putout](https://github.com/coderaiser/putout).

**Comment by bcoe** [comment]
@coderaiser thanks for the suggestion, and the patch 👍

Happy to add this feature, will merge once I can test this weekend, or early next week.

**Comment by coderaiser** [comment]
Nice :), this feature would by very useful, when you have `1500` files and suddenly some of them not fully covered, you should scroll a lot to see where is the problem :)

**Comment by RastaAlex** [comment]
👍👍👍

**Comment by XhmikosR** [comment]
@bcoe  this can be closed since it was released in v7.6.0. :)
