### ISSUE TITLE
Performance / optimizations with coverage enabled

### ISSUE THREAD

**Issue by schuay** [bcoe/c8#3]
Opening a new ticket here to avoid derailing https://github.com/nodejs/node/issues/16531:

> code transpiled for test coverage runs significantly slower than the code prior to transpilation; I'm betting collecting coverage directly from v8 will be fast (although the subprocess shenanigans might add some overhead).

Turning on code coverage disables optimization in many cases. It may be possible to allow optimization in some modes (e.g. precise binary coverage, or possibly all detailed coverage modes), but this probably requires investigation.

**Comment by shinnn** [comment]
Fixed in https://github.com/bcoe/c8/commit/3c1b92b621b7f18f9927395a7e95dc8ac73f0bc7.

**Comment by bcoe** [comment]
@shinnn these performance issues actually related to V8, so up until recently still effected c8, _however!_, @schuay recently took on addressing these issues:

https://bugs.chromium.org/p/v8/issues/detail?id=9148

so I believe this can remain closed \o/
