### ISSUE TITLE
[Edit] no coverage when running on Alpine

### ISSUE THREAD

**Issue by chriscapaci** [bcoe/c8#30]
I'm trying to upgrade from v2 to v3.2 and I'm not getting any coverage files generated anymore. With v2, when I run my mocha tests through c8, coverage files are generated in the set temp directory and then a report is generated in ./coverage. With v3.2, no coverage files are generated in the temp directory (which is what NODE_V8_COVERAGE is set to). 

This is what Node's docs say about NODE_V8_COVERAGE:

> NODE_V8_COVERAGE will automatically propagate to subprocesses, making it easier to instrument applications that call the child_process.spawn() family of functions. NODE_V8_COVERAGE can be set to an empty string, to prevent propagation.

>At this time coverage is only collected in the main thread and will not be output for code executed by worker threads.

I would think mocha would work within those conditions, but something isn't working properly. I don't know anything about the internals of mocha, but is it possible they don't run on the "main thread"? I'll try looking in to it, but I just wanted to point this out. I've been getting unit test code coverage with c8 v2 (with a few issues, but still generally decent reports except the function reports), but with v3.2, nothing. I'll have to stick with v2 for now. If you know anything about what may be going on, please let me know. Thanks.

**Comment by bcoe** [comment]
@chriscapaci *bump*, still running into issues?

**Comment by onip** [comment]
I am running into this issue: the same codebase works correctly when run inside node:10.11.0-alpine Docker image, while on node:10.12.0-alpine it shows 0% coverage.

I am using the ```text``` reporter and ```c8 mocha``` as test run command

if there's something more I can provide to help debugging the issue let me know.

**Comment by onip** [comment]
```
# npm ls mocha c8
+-- c8@3.2.0 
`-- mocha@5.2.0
```

**Comment by shinnn** [comment]
Closing, as no one provides a working demo although @beoe repeatedly asked the issue author to create it.

If someone creates a repository that can help reproduce the bug, I'll reconsider reopening this issue.
