### ISSUE TITLE
support shorthand for 100% test coverage check

### ISSUE THREAD

**Issue by gr2m** [bcoe/c8#329]
* **Version**: v16.9.1
* **Platform**: Mac OS X 10.15.7 (19H1417)

I really like [`tap`'s `--100` flag](https://node-tap.org/docs/coverage/100/). Could we add something similar to `c8`? It would turn

```
c8 --check-coverage --lines 100 --functions 100 --branches 100 --statements 100  node test.js
```

into 

```
c8 --100 node test.js
```

**Comment by bcoe** [comment]
@gr2m I like this idea 👍

**Comment by gr2m** [comment]
@bcoe I'm not quite sure how the `--check-coverage` parameter works.

I we want support both

1. `c8 check-coverage --100` 
2. `c8 --100 npm test`

but I'm not sure how. I tried to use `yargs.middleware()` but the code does not seem to be executed at all. See my WIP PR at https://github.com/bcoe/c8/pull/332
