### ISSUE TITLE
Question: How to merge coverage reports

### ISSUE THREAD

**Issue by Kikobeats** [bcoe/c8#336]
Hello,

I want to replace nyc for c8, but I found a scenario and I'm not sure if it's already covered (never better said) by the tool.

My [metascraper](https://github.com/microlinkhq/metascraper) project is a monorepo. It has a [packages](https://github.com/microlinkhq/metascraper/tree/master/packages) directory where every folder there is published as an independent npm package.

In order to get the coverage of the whole repo, I have a [script](https://github.com/microlinkhq/metascraper/blob/master/scripts/merge-reports) that uses `nyc merge` command to merge individual reports into once.

is it a convenient way to do the same using c8? If not, maybe could be an interesting command to add.

**Comment by bvanjoi** [comment]
I think you can put c8 in the root directory, then create a [bulk command](https://rushjs.io/pages/maintainer/custom_commands/), such as `test`, then execute `c8 npm run test`, finally a global report will generated.

**Comment by Kikobeats** [comment]
wow thanks for the reply. I did that and not just dropped a lot of lines in my codebase, also the coverage has been improved:
https://github.com/microlinkhq/metascraper/pull/486#issuecomment-991977938

I'm not sure how much accurate is that compared with nyc; I read both coverage tools are using similar principles

**Comment by bvanjoi** [comment]
Perhaps it's because `c8` doesn't count the files being imported.

**Comment by aabccd021** [comment]
I managed to merge the coverages by merging the temp directory
```bash
rm -rf coverage/tmp && mkdir -p coverage/tmp && c8 --report-dir coverage/foo runFoo && c8 --report-dir coverage/bar runBar && cp -r coverage/*/tmp/. coverage/tmp && c8 report
````
