### ISSUE TITLE
Broken link to the list of default excludes in README.md

### ISSUE THREAD

**Issue by katagawa** [bcoe/c8#337]
* **Version**: v7.10.0
* **Platform**: all

In https://github.com/bcoe/c8/blob/main/README.md, the link to the list of default excludes is broken. The working version of the link is https://github.com/istanbuljs/schema/blob/master/default-exclude.js

**Comment by bcoe** [comment]
@katagawa thanks for pointing this out, would happily take a patch if you're so inclined.

**Comment by XhmikosR** [comment]
This seems to be fixed on main.
