### ISSUE TITLE
Ignore Yarn 2+ Berry generated files

### ISSUE THREAD

**Issue by azat-io** [bcoe/c8#341]
After installing dependencies Yarn Berry generating two files in the root of a project: `.pnp.cjs` and `.pnp.loader.mjs`

How can I ignore this files? I cannot use `/* c8 ignore */` comments because this files are in `.gitignore`

**Comment by bcoe** [comment]
@azat-io you should be able to add `.pnp.cjs`, and `.pnp.loader.mjs` to a list of excluded files, something like this:

```js
  "exclude": [
    ".pnp.cjs",
    ".pnp.loader.mjs",
    "**/*-test",
    "**/.coverage",
    "**/apis",
    "**/benchmark",
    "**/conformance",
    "**/docs",
    "**/samples",
    "**/scripts",
    "**/protos",
    "**/test",
    "**/*.d.ts",
    ".jsdoc.js",
    "**/.jsdoc.js",
    "karma.conf.js",
    "webpack-tests.config.js",
    "webpack.config.js"
  ],
```

In your `.nycrc`. Let me know if this does the trick for you?

**Comment by azat-io** [comment]
Thanks!

**Comment by bcoe** [comment]
@azat-io going ahead and closing, let me know if you have any issues configuring.
