### ISSUE TITLE
Support descriptions at end of ignore directives

### ISSUE THREAD

**Issue by brettz9** [bcoe/c8#358]
* **Version**: 14.17.1
* **Platform**: Mac OSX

It'd be nice to support--as is enforced by [eslint-plugin-eslint-comments](https://mysticatea.github.io/eslint-plugin-eslint-comments/rules/require-description.html) for ESLint directives--the ability to add in descriptions at the end of c8 ignore directives so as to describe what is justifying ignoring the given block of text.

Developers may be deterred from removing an ignore directive which may no longer be needed or which may not have been justified for ignoring in the first place if they have to dig more deeply and blindly into why some block of code was ignored from coverage.

The [ignore option](https://mysticatea.github.io/eslint-plugin-eslint-comments/rules/require-description.html#options) for the above-mentioned ESLint tool would be especially useful with this feature (would help to ensure that all comments followed this practice).

Thanks!

**Comment by peterflynn** [comment]
Looks like this is the same request as #181.

**Comment by brettz9** [comment]
Yup, sorry, closing as dupe. Would be marginally convenient if that issue implemented in a way so as to allow two hyphens as separator so that the ESLint rule I mentioned could pick it up, but I know such existing tool support is a more marginal concern.
