### ISSUE TITLE
Allow to set NodeJS options

### ISSUE THREAD

**Issue by jcubic** [bcoe/c8#373]
* **Version**: `C8 7.11.0; Node v17.4.0`
* **Platform**: `Linux rwauwprlc0058 5.4.0-100-generic #113-Ubuntu SMP Thu Feb 3 18:43:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

I have unit tests using ava and one test is failing to fail. Because NodeJS probably increased the stack size limit. I have a Scheme interpreter in JavaScript and I'm executing `(! 1000)`, without TCO (tail call optimizations) it should overflow the stack. I want to hardcode the stack size with an option, so my tests are independent of the environment. But I'm not able to set it:

I've tried:

```bash
c8 node --stack-size=512 ./node_modules/.bin/ava
## Error [ERR_WORKER_INVALID_EXEC_ARGV]: Initiated Worker with invalid execArgv flags: --stack-size=512
node --stack-size=512 ./node_modules/.bin/c8 ava
## this flag is ignored because ava is executed without options
```

**Comment by rohit-gohri** [comment]
Can use NODE_OPTIONS env var for this, I have used the same for other tools like `ts-node` and `nodemon`

**Comment by jcubic** [comment]
Unfortunately, Node doesn't support `--stack-size` setting in NODE_OPTIONS.

**Comment by slickss-nsul** [comment]
@jcubic 

We had the need to increase the heap space, so we did this, which worked fine. your problem could be solved perhaps like so:

`node --stack-size=512 $(npm bin)/c8 ...`

We have that package globally installed, so for us it would be `node --stack-size=512 /usr/bin/c8 ...`

This works, because c8 is just a script, and so, you can just execute it with regular `node` and do what you like

**Comment by jcubic** [comment]
@slickss-nsul thanks, will try.

**Comment by jcubic** [comment]
It seems that `--stack-size` doesn't with Node 18 anymore.

**Comment by jcubic** [comment]
It doesn't work, and I don't see it in node help. Maybe they removed that option.

**Comment by jcubic** [comment]
`--stack-size` works in Node 18 but `node --stack-size=512 $(npm bin)/c8` doesn't. At last with the version of C8 I'm testing.
