### ISSUE TITLE
Erroneous report of missing coverage

### ISSUE THREAD

**Issue by faustbrian** [bcoe/c8#399]
* **Version**: v16.13.1
* **Platform**: Darwin Brians-MacBook-Pro-2.local 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000 arm64

I'm currently running into an odd issue with coverage reporting that affects every file. All my code has 100% test coverage but the top import of every file is marked as a branch that does not have coverage. I generate the reports via `c8 -r html --src=source uvu -r tsm source .test.ts`.

<img width="330" alt="CleanShot 2022-05-08 at 08 54 15@2x" src="https://user-images.githubusercontent.com/22145591/167283810-2f0fee1f-82db-4117-bc70-d10458129b0e.png">

Is this a known issue or something I can work around somehow? At the moment I'm adding ignore statements on top of every file to ignore the first line but that's rather tedious and would ideally not be needed because everything is covered with tests.

**Comment by bcoe** [comment]
@faustbrian would you be able to provide a minimal product that exhibits this behavior? 

My bet is it has to do with how `tsm` transplies the file, such that there's perhaps a guard on the import -- is it possible to see the JS code trnaspiled by tsm?
