### ISSUE TITLE
Add watermarks CLI flags

### ISSUE THREAD

**Issue by ehmicky** [bcoe/c8#40]
The `report` command has a `watermarks` option, but it cannot be specified using the CLI because no `yargs` option for `watermarks` is defined.

There probably should be `--statements`, `--lines`, `--functions` and `--branches` CLI options.

**Comment by bcoe** [comment]
@ehmicky would happily accept help adding this feature; we should be able to port over the functionality from nyc:

https://github.com/istanbuljs/nyc

**Comment by ehmicky** [comment]
I just checked and `watermarks` actually works, it's just not documented by `yargs`. Sorry about that!
