### ISSUE TITLE
Source folder deleted because I am stupid. But then again why there is no option for not generating coverage folder?

### ISSUE THREAD

**Issue by lillallol** [bcoe/c8#400]
Reading the output from:

```bash
npx c8 --help
```

I found no way to not generate the `./coverage` folder.

But there is no problem with that. I can just use an npm script like this:

```txt
coverage : c8 npm run test; rm -rf ./coverage;
```

and one day (like today) I will decide to produce code coverage for only the `./src` folder and like the smart guy I am, I will do :

```
npm run coverage -- src
```

and... source folder irreversibly deleted. I lost some brain cells today for that source folder.

Why there is no option for not generating coverage folder?

The whole cli API is counter intuitive. --100 is a thing but a custom value like --95 is not. 

Why?

**Comment by bcoe** [comment]
> and... source folder irreversibly deleted. I lost some brain cells today for that source folder.

I'm sorry this happened to you, this stinks :(

> why there is no option for not generating coverage folder?

The coverage folder is necessary because of how c8 works. When Node.js is running, raw coverage data is output from v8 to disk (in `coverage/tmp`). When `c8` finishes running, this is then the folder that pretty coverage reports are output in, and where coverage information is calculated, based on the tmp files.

**Comment by bcoe** [comment]
> Why is --100 is a thing but a custom value like --95 is not.

This is more of a feature request for yargs, `--100` is specifically configured as an argument, to support every numeric option I would need to configure arguments for `--99`, `--98`, `--97`, `--96` etc.

--

Please feel free to open issues for specific feature requests, e.g., cleaning up the `coverage` folder after execution.
