### ISSUE TITLE
Travis badge is green, however build log indicates a failure

### ISSUE THREAD

**Issue by weswigham** [bcoe/c8#42]
The travis badge on the readme is green, which makes you think the build is solid, but the [actual log](https://travis-ci.org/bcoe/c8/jobs/444460241#L452) indicates an early failure from an uncaught promise rejection (which does not currently trigger a nonzero exit code)!

**Comment by weswigham** [comment]
It looks like [this commit](https://github.com/bcoe/c8/commit/23e5da63a45fcebcc692e54c13732fa0af20f821) first introduced the issue.

**Comment by bcoe** [comment]
@weswigham this oddity looks to have been addressed, thanks for the bug report.
