### ISSUE TITLE
Support for Node's new built-in test runner (node --test)

### ISSUE THREAD

**Issue by AviVahl** [bcoe/c8#424]
* **Version**: 18.12.0
* **Platform**: Linux fedora 6.0.5-200.fc36.x86_64 

Node 18 now has a built-in test runner. It has also been back-ported to 16.
I've tried using c8 with it, and all I get is:
```
> c8 node --test --enable-source-maps

----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |       0 |        0 |       0 |       0 |                   
----------|---------|----------|---------|---------|-------------------
Segmentation fault (core dumped)
```

Steps to reproduce:
- clone https://github.com/wixplosives/sample-monorepo
- `npm i c8 -D`
- open `package.json` and edit `test:node`. prefix it with `c8` so it says: `"test:only": "c8 node --test --enable-source-maps",`
- `npm t`

**Comment by bcoe** [comment]
I believe this is caused by:

https://github.com/nodejs/node/issues/45013

And can't be fixed in c8 itself. You can confirm by running your tests with `NODE_V8_COVERAGE=/tmp/coverage`, without `c8`.

**Comment by AviVahl** [comment]
Thanks for the info. I'll try again with the next node version.
