### ISSUE TITLE
Allow configuration file to be extended

### ISSUE THREAD

**Issue by blephy** [bcoe/c8#425]
I,

It would be great to be able to `extends` a configuration file to another, like `TSConfig` or `Eslint` do, or at least to be able to write `.cjs` / `.js` configuration file to require another `js` file.

We use c8 in a mono-repo, and we cannot share a c8 configuration file between workspace:/

Thanks

**Comment by bcoe** [comment]
This seems like a good feature request 👍

**Comment by blephy** [comment]
Do you need some help ?

**Comment by blephy** [comment]
@bcoe i did look to the c8 and yargs code. In fact, we can already extends configuration if the path to the extendable config is a `json` file.

This is already working : 

```json
{
  extends: '../../config/c8/c8.config.json',
  // ...
```

What about making c8 compatible with yml and js configuration ? [cosmiconfig](https://github.com/davidtheclark/cosmiconfig) sounds good for this.

**Comment by bcoe** [comment]
Closing in favour of:

https://github.com/bcoe/c8/issues/431

With regards to cosmicconfig, I would prefer not to pull in a dependency for config management, if it can be avoided. I think it's not worth the complexity it would add to the library.

> Additionally, we should update the documentation. I did a branch but cannot push to this repository :/

You will need to create a pull request form a fork, [here's some documentation on how to do so](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork) 👍
