### ISSUE TITLE
v8-to-istanbul relies on file://

### ISSUE THREAD

**Issue by bathos-wistia** [bcoe/c8#43]
(Don’t think this is significant, but:)

* **Version**: 10.13.0
* **Platform**: Darwin

In v8-to-istanbul, the presence of `file://` in the specifier is used to determine whether or not the CJS header should be used to offset the results:

https://github.com/istanbuljs/v8-to-istanbul/blob/v1.2.1/lib/script.js#L120-L125
https://github.com/istanbuljs/v8-to-istanbul/blob/v1.2.1/lib/script.js#L13-L16

In c8, the specifier is resolved to a non-URL filepath before being passed to v8-to-istanbul:

https://github.com/bcoe/c8/blob/v3.2.1/lib/report.js#L51-L52

ESM modules that were run natively as ESM get interpreted as CJS as a consequence — incorrect offsets get applied to all ranges. When this is changed so that the original specifier is used the ranges are correct.

This behavior was introduced in 3.2.1 when trying to solve for a different issue related to file: specifiers. It seems like file: is probably not a good signal to rely on for determining ESM vs CJS, but it also appears that there’s nothing better available to v8-to-istanbul presently.

**Comment by demurgos** [comment]
Thanks for reporting the issue on Github. The maintainers are aware of it.

Given the current design of `c8`, I'd propose the following solutions:
- Short term: switch the module type detection to use the extension (`.mjs` or not).
- Longer term: Allow the user to configure the module type for each file (for example using a glob).

Also note that the inspector API exposes the module type in the parse event but this information is not stored in the process coverage generated by Node.

**Comment by bcoe** [comment]
@bathos-wistia newer versions of `c8` (`npm i c8@next`) no longer perform this detection, instead you can specify `--wrapper-length` if you have a non-default wrapper, let me know how this works for you?

**Comment by shinnn** [comment]
Fixed in v3.3.0, as @bcoe said.
