### ISSUE TITLE
How to generate report for active node server?

### ISSUE THREAD

**Issue by cion-yatindra** [bcoe/c8#438]
* **Version**: 16.18.0
* **Platform**: Ubuntu 20.04 x86_64 GNU/Linux

Hi, 
I want to use c8 for checking code coverage for my typescript based node server. 
My use case is:
1. Frontend will have test scripts which will try to cover maximum APIs.
2. We want to start server in usual way along with c8, with command similar to `c8 node --loader ts-node/esm app.ts`.
3. Now when the frontend tests gets completed, I want to somehow generate the code coverage reports for the server. 

Issue:
Right now from what I have read till now, I need to gracefully exit the server using `process.exit(0)` post which c8 generates the report. But for doing this, it would require to exposing an API which calls process.exit(). This temporary solution works but it doesn't seem to be ideal way. I tried using `kill {PID}` commands and usual `CTRL + C` to end the server but none of them works.  Am I missing something or is there any better way to generate report?

**Comment by cion-yatindra** [comment]
Thanks for suggestion @olivierodo . I found another way by creating a restricted api and simply called `v8.takeCoverage()` which takes the coverage even while the server is running. And then `c8 report` for using this coverage for further usage.

**Comment by olivierodo** [comment]
Hi @cion-yatindra, it's sounds like an interesting approach may i ask for more details i might be interested to try this approach on my project.

**Comment by cion-yatindra** [comment]
Hi @olivierodo , For my node server, i created an api as
```
import v8 from 'v8';

.... server setup ...
 const app = express(); 
app.post('/coverage', async (req, res)=>{
        ... some authentication here or in middleware ....
        v8.takeCoverage();
        v8.stopCoverage();
        res.sendStatus(200);
} );
````
Run server as `c8 node app.js`.
Then start testing from frontend (my use case).
Call this `/coverage` api at end of testing directly from frontend.
In server terminal, run `c8 report`.


After calling this API, the v8 code coverage JSON is generated at directories mentioned in c8 config.

Let me know if you need more details.

**Comment by olivierodo** [comment]
thanks @cion-yatindra, I thought you found a way to do it without including a new endpoint in the server.
But I didn't now the v8 functions, i'll try to play around with it. 🙏
