### ISSUE TITLE
Wrong ranges

### ISSUE THREAD

**Issue by anurbol** [bcoe/c8#44]
Not necessarily relates to c8, but I was [asked](https://github.com/nodejs/node/issues/22919#issuecomment-439616251) to create an issue here.

I have general struggle with coverage features in node.js.

I tried using c8 package and node.js' inspector [module](https://nodejs.org/api/inspector.html).
Neither of them gives correct `lineNumber`, `columnNumber` and `ranges` (`startOffset`, `endOffset`), unfortunately. 

## c8

when I run `c8 node test.js` where test.js is this file:

```js
function foo() {
  console.log(123)
}

foo()
```
I get this in the generated report:
```json
{"functionName":"foo","ranges":[{"startOffset":62,"endOffset":99,"count":1}]
```
Note the `startOffset":62` when there is 44 characters total in `test.js`. I am not even speaking about `"endOffset":99`.

## inspector

after not successing with c8 I tried to place in my test.js code from this [example](https://nodejs.org/api/inspector.html#inspector_cpu_profiler)

and run `node test.js`
then I got this: 
```json
{"functionName":"session.post","scriptId":"66","url":"file:///home/nurbol/www/sandbox/test.js","lineNumber":5,"columnNumber":32},"hitCount":0,"children":[16]}
```
Note the `"lineNumber":5` when there is no anything on line number 5!

Then @bcoe gave me an [advice](https://github.com/nodejs/node/issues/22919#issuecomment-439613062) to take into accunt `require('module').wrapper[0]` that is inserted by node.js. But if done so, line number 5 contains `session.connect` and not `session.post` (see the json above)!

**My setup:**

Linux (Lubuntu).
Node 11.2.0 (also tested in 10.13.0 with the same results)
c8 3.2.1

**Comment by bcoe** [comment]
this is a bug with the header not being removed, because of a breaking change in Node.js around module naming; it will be fixed in future node versions when wrapping behavior changes — the 62 characters is module.wrap not being removed from the offsets.

**Comment by anurbol** [comment]
However `lineNumber` and `columnNumber` in my second example (using **inspector** module of node.js) still do not make any sense...

**Comment by shinnn** [comment]
I'm closing this because Node.js v12 has been released.

If you still run into this problem even if you use Node.js v12, feel free to comment more here.
