### ISSUE TITLE
Empty lcov if source code using `.mts`

### ISSUE THREAD

**Issue by loynoir** [bcoe/c8#461]
### Reproduce
```json
  "c8": {
    "report-dir": "./build/coverage",
    "reporter": ["lcov"]
  },
  "scripts": {
    "test": "c8 tsx --test-reporter spec path/to/foobar.test.mts"
```

```sh
$ npm test
...
$ grep SF: build/coverage/lcov.info
$
```

### Workaround
```json
  "c8": {
    "report-dir": "./build/coverage",
    "reporter": ["lcov"],
    "extension": [".mts",".cts", ".ts", ".mjs", ".cjs", ".js"]
  },
  "scripts": {
    "test": "c8 tsx --test-reporter spec path/to/foobar.test.mts"
```

```sh
$ npm test
...
$ grep SF: build/coverage/lcov.info
SF:path/to/foo.mts
SF:path/to/bar.mts
```

### Suggestion
Add next generation typescript extensions to default config.

### What changed
- node loader now chainable, or said more usable https://nodejs.org/dist/latest-v18.x/docs/api/esm.html#loaders
- typescript introduce next generation extension like `.mts` `.cts`

### Related
https://github.com/bcoe/c8/issues/429

**Comment by SmashingQuasar** [comment]
@loynoir #429 is resolved thanks to the suggested solution if you want to look at it.
