### ISSUE TITLE
Internal: Integration tests do not properly exclude the library files

### ISSUE THREAD

**Issue by demurgos** [bcoe/c8#47]
The following integration test produces a snapshot:
https://github.com/bcoe/c8/blob/36797341d73c47e226c130cce7389ca1395c5df3/test/integration.js#L26

Here is the corresponding snapshot:
https://github.com/bcoe/c8/blob/36797341d73c47e226c130cce7389ca1395c5df3/test/integration.js.snap#L8-L22

Expected:
- The snapshot only contains a report for the files in the `fixtures` directory.

Actual:
- The snapshot contains a report with the `lib` files.

This causes noise in PRs. Every time the lib is changed, the snapshot must be regenerated (even if you just add whitespace or a comment).

**Comment by shinnn** [comment]
Fixed in https://github.com/bcoe/c8/commit/51a9fa75c36c18608b4937c24be8842f3c7054c9.
