### ISSUE TITLE
Unable to get report for a node server

### ISSUE THREAD

**Issue by iamthadiyan** [bcoe/c8#55]
* **Version**:node v8.11.1
* **Platform**:Ubuntu 16.04LTS

I am trying to use c8 on a node server. I start the server like this `$ c8 node app.js` . After this I run my BDD tests on this server. Once I am done, I will stop the server by `Ctrl+C`. But when I run `$ c8 report`, I do not see any report.

What am I missing here? Please help.

Context: I am running the node server on a docker and BDD is initiated from another BDD docker. So I am looking for a way to generate code coverage report without modifying the server code base much.

**Comment by bcoe** [comment]
👋 hey @iamthadiyan, unfortunately c8 only works for Node.js `>= 10.12.0`; your best bet would probably be simply running your server on one of these newer Node.js versions with `NODE_V8_COVERAGE` enabled.

And then using the `c8 report` functionality.
