### ISSUE TITLE
throw results in an uncovered line

### ISSUE THREAD

**Issue by coreyfarrell** [bcoe/c8#58]
* **Version**: v11.7.0
* **Platform**: Linux lt2 4.19.8-200.fc28.x86_64 #1 SMP Mon Dec 10 15:43:40 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

```js
function testThrow(doThrow) {
	if (doThrow) {
		throw new Error('test throw');
	}
}

testThrow(true);
```

Run the above under c8, it reports that line 4 is not covered.  Really since line 4 is only a `}` I think it should not even count, having no `else` statement means that line is non-significant.  IMO significance of lines comment applies to lines 5 and 6 as well, the `}` of a function does not have any actual code.  Line 6 is blank so that should not be counted.

`nyc` basically works the way I expect, though the `function testThrow(doThrow) {` line isn't part of the total or covered lines.  I don't have a strong opinion about counting / not counting the function declaration as a line.

**Comment by coreyfarrell** [comment]
Turns out it's not just throw which does this.  The following code does the same thing - the `}` of the if block cannot be covered.

```js
function testReturn(doReturn) {
	if (doReturn) {
		return;
	}
}

testReturn(true);
```

**Comment by shinnn** [comment]
As far as I investigated, with Node.js v11.13.0, the code on both https://github.com/bcoe/c8/issues/58#issue-401152736 and https://github.com/bcoe/c8/issues/58#issuecomment-456244083 are regarded as 100%-covered by `c8`.

**Comment by coreyfarrell** [comment]
@shinnn confirmed, thanks for pointing this out.

**Comment by bcoe** [comment]
@coreyfarrell @shinnn awesome \o/ glad to see some of these issues being resolved.
