### ISSUE TITLE
Incorrect coverage reported for ternaries in some situations

### ISSUE THREAD

**Issue by Trott** [bcoe/c8#61]
* **Version**: 11.9.0
* **Platform**: Darwin Fhqwhgads.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Dec 20 21:47:19 PST 2018; root:xnu-4570.71.22~1/RELEASE_X86_64 x86_64

In file `foo.js`:

```js
'use strict';

function testIt (a, b) {
 const thing = a && b;
 console.log(thing);
 return a && b;
}

if (testIt(true, false))
  console.log('foo');
```

I run this:

```bash
c8 node foo.js
```

I get this:

```console
false
----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |      100 |       60 |      100 |      100 |                   |
 foo.js   |      100 |       60 |      100 |      100 |              6,10 |
----------|----------|----------|----------|----------|-------------------|
```

I would have expected the coverage for line 4 (the assignment to `thing`) and line 6 (the `return` statement) to be the same. Instead, it is (correctly) reporting that 6 has some uncovered branches, but is omitting the same thing for line 4.

**Comment by Trott** [comment]
@bcoe

**Comment by bcoe** [comment]
@Trott thanks for filing; @JaKXz for this sort of problem, we'll probably want to look first at the output from V8, and see if the offsets are actually wrong -- if they look right in V8, we know the problem is with our translation to line #s, if they are in fact wrong, we should create an upstream error report in https://bugs.chromium.org.

**Comment by bcoe** [comment]
did a little bit of testing with Node 13, and a slightly modified sample:

```js
'use strict';

function testIt (a, b) {
 const thing = a || b;
 console.log(thing);
 return a && b;
}

if (testIt(true, true))
  console.log('foo');
```

The coverage seems to work as I'd expect now 👍
