### ISSUE TITLE
Report directory can't be configured by CLI options

### ISSUE THREAD

**Issue by shonie** [bcoe/c8#64]
Version: v10.15.1
Platform: 4.18.0-14-generic #15-Ubuntu SMP Mon Jan 14 09:01:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Hello, @bcoe!

Thank you for so awesome tool. 

I have tried `c8` and it satisfies all my needs except one. 
I have to generate two reports (one for unit tests coverage, other - for functional tests coverage). But the output directory is hardcoded for each run (see [this line](https://github.com/bcoe/c8/blob/master/lib/report.js#L37)). So i am not able to collect artifacts on my CI for both: unit tests and functional tests. This is a very minor issue and if you don't mind, i will try to fix it and create a PR.

Best regards
shonie

**Comment by shinnn** [comment]
Fixed in https://github.com/bcoe/c8/pull/65.
