### ISSUE TITLE
Question: Does this work with codecov.io

### ISSUE THREAD

**Issue by styfle** [bcoe/c8#71]
Does c8 work with `codecov` package?

It looks like they expect the same output as `istanbul` from the readme: https://www.npmjs.com/package/codecov

But I'm not sure the differences in the outputs or how to get c8 to change the output.

Thanks!

**Comment by eight04** [comment]
I have some projects using c8 + travis + codecov. However, it seems that the line number is wrong. Here is an example:
https://codecov.io/gh/eight04/idb-storage/src/master/index.js

**Comment by bcoe** [comment]
@eight04 @styfle this should work with `codecov`, try using `-reporter=text-lcov` for output? exactly the same as nyc.

**Comment by eight04** [comment]
I have already used the `text-lcov` format in travis. Log:
https://travis-ci.com/eight04/idb-storage

c8 v3.4.0
https://github.com/eight04/idb-storage/blob/11d650c70da907e04971e76d0573588ce22a1d74/package.json#L30

**Comment by JaKXz** [comment]
I would change it to `c8 --reporter=lcov npm test && npx codecov` -- without any options codecov expects the coverage file to be in `./coverage/lcov.info`. With this reporter you get the html report and the codecov file that you need.

**Comment by eight04** [comment]
[I made a PR](https://github.com/eight04/idb-storage/pull/5) updating c8 to 0.3.5, changing the format to lcov, and drop the `c8 report` command. The line number is corrected now:
https://codecov.io/gh/eight04/idb-storage/pull/5/src/index.js

Travis log:
https://travis-ci.com/eight04/idb-storage/builds/108787127

**Comment by styfle** [comment]
It looks like `c8` works fine because I get an html report I can view in my browser after running `npx c8 --reporter=lcov npm test && npx codecov`.

So there must be a bug in the `codecov` package because files upload successfully and a url is generated for the commit, but visiting the url says there was an error processing reports.

```
npx: installed 21 in 1.582s
  _____          _  
 / ____|        | |  
| |     ___   __| | ___  ___ _____   __  
| |    / _ \ / _` |/ _ \/ __/ _ \ \ / /  
| |___| (_) | (_| |  __/ (_| (_) \ V /  
 \_____\___/ \__,_|\___|\___\___/ \_/  
                                v3.3.0
==> Detecting CI Provider
    Circle CI Detected
==> Configuration: 
    Endpoint: https://codecov.io
{ commit: 'd9f760b1523acec516084cb0453ca824950f3f17',
  branch: 'circleci',
  package: 'node-v3.3.0' }
==> Building file structure
==> Generating gcov reports (skip via --disable=gcov)
    $ find /home/circleci/repo -type f -name '*.gcno'  -exec gcov  {} +
==> Scanning for reports
    + /home/circleci/repo/coverage/lcov.info
==> Uploading reports
    Success!
    View report at: https://codecov.io/github/zeit/tracing-js/commit/d9f760b1523acec516084cb0453ca824950f3f17
Done in 9.27s.
```

**Comment by bcoe** [comment]
@styfle did you try `text-lcov` like the `nyc` example.

**Comment by styfle** [comment]
@bcoe Same problem

![image](https://user-images.githubusercontent.com/229881/56380534-66656380-61e0-11e9-8069-55c898cd6bd1.png)

**Comment by JaKXz** [comment]
> same problem

because text-lcov does not output the `lcov.info` file in the same place that the lcov reporter does.

**Comment by bcoe** [comment]
@styfle @JaKXz text-lcov outputs an lcov report to the terminal, which I believe s service like coveralls should then allow you to pipe to it; here's what I do with coveralls.io:

`c8 report --reporter=text-lcov | coveralls"`

It looks like maybe codecov only accepts an uploaded file? so I guess the original approach you were taking looks more reasonable.

I'd need to play with codecov.io's interface, but I'm 99% sure the lcov info being output is correct.

**Comment by bcoe** [comment]
anyone happen to have codecov configured, and want to try c8 out?

**Comment by nevir** [comment]
It's working like a charm over here (private repo so I can't show the results).

Commands being run are:

```
c8 …run your tests… # We actually do this twice for two different test suites
c8 report --reporter=text-lcov > coverage/tests.lcov
codecov
```

**Comment by bcoe** [comment]
@styfle are you still having this problem? I believe I might have addressed it for our own use-cases at Google, I use this configuration:

```json
{
  "report-dir": "./.coverage",
  "reporter": ["text", "lcov"],
  "exclude": [
    "**/*-test",
    "**/.coverage",
    "**/apis",
    "**/benchmark",
    "**/docs",
    "**/samples",
    "**/scripts",
    "**/src/**/v*/**/*.js",
    "**/test",
    ".jsdoc.js",
    "**/.jsdoc.js",
    "karma.conf.js",
    "webpack-tests.config.js",
    "webpack.config.js"
  ]
}
```

and run the codecov upload bin.

**Comment by styfle** [comment]
@bcoe I'm not sure what file you posted above. Is this a c8 config file?

I tried the latest c8 and codecov cli via `npx` and it still fails. I suspect this is a problem with codecov because nyc also failed in the same way but their support has been busy for the last couple months 🤷‍♂ 

Can you see this [script](https://github.com/zeit/tracing-js/blob/ae84d956164161585dce891b4d28f55d8647d6a6/package.json#L16) and this [CI job](https://circleci.com/gh/zeit/tracing-js/18)?

I'm using `npx c8 --reporter=lcov npm test && npx codecov`.

**Comment by bcoe** [comment]
@styfle that is the `.c8rc.json` file, we use the public codecov bash script, with most of our libraries on github.com/googleapis, and it seems to work like a charm.

If you share a project with codecov failing, perhaps I could take a look. I also recommend opening an issue on codecov.

**Comment by styfle** [comment]
@bcoe Thanks for the help, I appreciate it!

The project is here: https://github.com/zeit/tracing-js

**Comment by styfle** [comment]
@bcoe I got it working by running tests with `ts-node` https://github.com/zeit/tracing-js/pull/26

Here's the script I used:

```
npx c8 --reporter=lcov tape -r ts-node/register test/**.ts && npx codecov
```
