### ISSUE TITLE
strange missing branch coverage at return statement

### ISSUE THREAD

**Issue by mknj** [bcoe/c8#72]
* **v10.15.1**:
* **Linux home 4.18.0-16-generic #17-Ubuntu SMP Fri Feb 8 00:06:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux**:

nyc reports 100% coverage when c8 reports only 75% coverage.

```
$ cat t.js 
t()
function t () {
  return 42
}
$ ./node_modules/.bin/c8 node t.js 
----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |      100 |       75 |      100 |      100 |                   |
 t.js     |      100 |       75 |      100 |      100 |                 3 |
----------|----------|----------|----------|----------|-------------------|

$ node --version
v10.15.1
$ ./node_modules/.bin/c8 --version
3.4.0

```

**Comment by mknj** [comment]
same for node v10.15.3.

0% Stmts, but 100% branch for node v11.13.0

**Comment by bcoe** [comment]
@mknj this is addressed by https://github.com/nodejs/node/commit/23ea7ee64b98218e06cf3217372ade7b401250f8 which shoudl be released in future v10.x releases -- the `return` logic was fixed in V8, but not back-ported to older Node.js versions yet.

Thanks for the bug report :smiley:

**Comment by shinnn** [comment]
https://github.com/nodejs/node/commit/23ea7ee64b98218e06cf3217372ade7b401250f8 is now included in the released Node.js versions.
