### ISSUE TITLE
missing coverage of closing brace when `return` ends a `switch/case`

### ISSUE THREAD

**Issue by Trott** [bcoe/c8#81]
* **Version**: tested on 8.15.1, 10.15.3, 11.14.0, 12.0.0, 13.0.0-pre
* **Platform**: Darwin Fhqwhgads.local 17.7.0 Darwin Kernel Version 17.7.0: Wed Feb 27 00:43:23 PST 2019; root:xnu-4570.71.35~1/RELEASE_X86_64 x86_64

Code in foo.js:

```javascript
function checkIt(arg) {
  switch (arg) {
    case true:
      return 'It was true!';
    case false:
      return 'It as not true';
  }
  return 'It was neither true nor false';
}

const val1 = checkIt(true);
const val2 = checkIt(false);
const val3 = checkIt('string');

console.log(val1);
console.log(val2);
console.log(val3);
```

Command:

```console
c8 node foo.js
```

Output:

```console
It was true!
It as not true
It was neither true nor false
----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |    94.12 |    71.43 |      100 |    94.12 |                   |
 foo.js   |    94.12 |    71.43 |      100 |    94.12 |                 7 |
```
```

Expected output:

I expected to see 100% coverage...

**Comment by bcoe** [comment]
```bash
It was true!
It as not true
It was neither true nor false
----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |    94.12 |    71.43 |      100 |    94.12 |                   |
 foo.js   |    94.12 |    71.43 |      100 |    94.12 |                 7 |
----------|----------|----------|----------|----------|-------------------|
```

I'm seeing line `7` missing coverage, which seems potentially like a bug in V8 -- I think that there's a chance your `0%` coverage is a configuration issue; can you share a repo with this bug?

**Comment by Trott** [comment]
@bcoe If I rename the file to `foo.js`, I get the results you show. I get 0% coverage if the file is named `test.js` which I guess is by design? Happy to provide a repo if it helps, but honestly, it's just the file contents shown above and nothing else.

**Comment by shinnn** [comment]
> which I guess is by design?

Yes.

```console
$ c8 --help
[...]
--exclude, -x      a list of specific files and directories that should be
                     excluded from coverage (glob patterns are supported)
                                                                    [Default:
  ["coverage/**","packages/*/test/**","test/**","test{,-*}.js","**/*{.,-}test.js
                 ","**/__tests__/**","**/node_modules/**","**/babel.config.js"]]
```

One of the default glob patterns `test{,-*}.js` matched `test.js` and it was excluded by chance.

**Comment by bcoe** [comment]
@Trott do we want to keep this open still? but perhaps be more specific, like closing `}` of switch statement is not covered?

**Comment by Trott** [comment]
> @Trott do we want to keep this open still? but perhaps be more specific, like closing `}` of switch statement is not covered?

¯\\_(ツ)_/¯  Seems like it might have the same root cause as #61 and/or #62? So if you wanted to close it as a probable-duplicate, I would be OK with that. But in the meantime, I'll update it....

**Comment by Trott** [comment]
(Updated. Might not be a bad idea to hide most of the subsequent comments as outdated or whatever.)

**Comment by bcoe** [comment]
@Trott thanks :+1: ... these bugs will probably ultimately be addressed in `V8`, but I'm happy to track here for the time being.

**Comment by Oloompa** [comment]
i meet similar issue

foobar.ts
```typescript
export function test_1(param: boolean) {
    switch (param) {
        case true:
            console.log("true");
            break;
        case false:
            console.log("false");
    }
}

export function test_2(param: boolean) {
    switch (param) {
        case true:
            console.log("true");
            break;
        default:
            console.log("false");
            break;
    }
}

export function test_3(param: boolean) {
    switch (param) {
        case true:
            console.log("true");
            break;
        default:
            throw new Error("error");
    }
}
```

test.ts
```typescript
import { test_1, test_2, test_3 } from "./foobar";

test_1(true);
test_1(false);
test_2(true);
test_2(false);
test_3(true);
try {
    test_3(false);
} catch (err) {
    console.log("error caught");
}
```

output
```shell
true
false
true
false
true
error caught

----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |       80 |    66.67 |      100 |       80 |                   |
 plop.ts  |       80 |    66.67 |      100 |       80 | 16,19,20,27,29,30 |
----------|----------|----------|----------|----------|-------------------|
```

![image](https://user-images.githubusercontent.com/51793308/64442525-37d52000-d0d0-11e9-9487-8d24fe42fe79.png)


It not only happens with return in switch statement.
it happens also if last item before braces is a `break;`
it happens also if last item before braces is a `throw`
It happens on `default` too

**Comment by Trott** [comment]
I think this has been fixed in V8 although awaiting a release?

**Comment by bcoe** [comment]
@Trott hey, I remember this bit of the codebase,

https://github.com/v8/v8/commit/deac757bc76d207845375340bcea090c774ad9d0

Let's cherry-pick that commit :smile:
