### ISSUE TITLE
bug: coverage reported incorrectly with source-maps on Node 12

### ISSUE THREAD

**Issue by bcoe** [bcoe/c8#90]
This is a strange one, for the following repo, which uses TypeScript and source-maps:

https://github.com/googleapis/release-please

coverage is reported correctly on Node 11, but does not seem to be correct on Node 12; it's over reporting.

@shinnn this seems like a high priority issue, as it leads to over reporting of coverage, which can give false confidence to users.

**Comment by shinnn** [comment]
A minimal reproduction helps us to tackle this.

**Comment by bcoe** [comment]
@shinnn if you:

`git clone` relese-please,
`nvm use 12`
`npm t`

The issue crops up in `changelog.ts`, I'll try to carve out a more minimal reproduction soon.

**Comment by shinnn** [comment]
I hope anyone can provide a small repo instead of a full project.

**Comment by bcoe** [comment]
@shinnn an update on this one, I can't seem to reproduce this issue on my home computer, even though I'm seeing the behavior on my Linux desktop and laptop at work:

<img width="666" alt="Screen Shot 2019-05-04 at 11 39 36 AM" src="https://user-images.githubusercontent.com/194609/57183405-85f7bf80-6e61-11e9-89da-a28cb2e1da7c.png">

**Comment by bcoe** [comment]
Here's logs demonstrating that the issue *does* sometimes occur though:

https://source.cloud.google.com/results/invocations/c9c47dfa-73a9-4ae4-9ad9-49c30f85a6a5/log

Note the `96.18%` coverage for `conventional-commits.ts` which is over-reporting.

**Comment by bcoe** [comment]
Fascinating, the issue happens on `Node@11.10.1`, but not `Node@11.13.0`; I think we're on the right track here.

**Comment by Saul-Mirone** [comment]
I meet something strange: When I check coverage of js files generated from ts with source-map, I got something not covered like this:
```typescript
@Resolver()
export default class CategoryResolver {
  @InjectRepository(Category)
  private readonly categoryRepository!: Repository<Category>;

  @Query((_) => [Category])
  public async categories() {
    const categories = await this.categoryRepository.find();

    return categories;
  }
} // **this line not covered**
```
The end brace is always not covered, is that the same problem like this issue?

**Comment by bcoe** [comment]
@Saul-Mirone this is a fairly specific issue related to missing functions in Node 12 environments, this sounds like an off by one error (which might either be in c8, or in V8 itself).

Mind opening another issue, with a minimal reproduction if possible?

**Comment by bcoe** [comment]
this was ultimately addressed upstream in v8.
