### ISSUE TITLE
does not verify all conditions when || present

### ISSUE THREAD

**Issue by Trott** [bcoe/c8#93]
* **Version**: 12.2.0
* **Platform**: Darwin LIB-0F7FVH8-LT 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64

foo.js:

```javascript
function test(a,b) {
  if (a || b) {
    return true;
  }
  return false;
}

test(true, false);
test(false, false);
```

Command + output:

```console
$ npx c8 node foo.js
npx: installed 123 in 3.436s
----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |      100 |      100 |      100 |      100 |                   |
 foo.js   |      100 |      100 |      100 |      100 |                   |
----------|----------|----------|----------|----------|-------------------|
$ 
```

Expected results:

I expected the branch coverage to be less than 100% because in `a || b`, the condition never occurs where `b` is `true`. `nyc` is showing the same behavior so maybe I'm confused? But it sure seems like [the `nyc` documentation suggests this should not show 100% coverage](https://github.com/gotwarlost/istanbul/blob/master/ignoring-code-for-coverage.md#ignore-specific-conditions-in-an-expression). Anyway, not sure if the problem is my repro, my expectations, or if it's a bug in V8 and/or c8 and/or nyc/istanbul. Help?

**Comment by Trott** [comment]
Oh, it's a bug in V8/Node.js, it would seem. Coverage is as expected in Node.js 10.x. Problem appears in Node.js 11.x and is also in Node.js 12.x. At least that's what I"m seeing....

**Comment by Trott** [comment]
(Although 10.x has other coverage-reporting problems that have since been fixed, so it reports the wrong stats for this code too, just wrong in the other direction....)

**Comment by demurgos** [comment]
The result is consistent with nyc/istanbul. Here is the result with nyc/istanbul:

![image](https://user-images.githubusercontent.com/2262218/57493906-48fb5500-72c7-11e9-83bc-79af2255055f.png)

c8 and istanbul check which part of the program were evaluated, not why. `return true` is evaluated during the first call; `|| b` and `return false`; are evaluated during the second call.

**Comment by Trott** [comment]
Makes sense to me. Will close.

**Comment by AnyhowStep** [comment]
Expression-level code coverage would be nice to have. I know for a fact I haven't tested some sub expressions (in a complex boolean expression) but I'm getting 100% coverage.
